USE ANUP;
SHOW TABLES;

DELIMITER $$
CREATE PROCEDURE getsomedata1()
BEGIN
	SELECT * FROM STUDENTS;
	SELECT * FROM COURSES;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE getsomedata(IN ID INT)
BEGIN
	SELECT * FROM STUDENTS WHERE STUDENT_ID=ID;
	SELECT * FROM COURSES;
    SELECT * FROM CITIES;
END $$
DELIMITER ;

call getsomedata(101);